const NorderAttrb = [
    "orders.id",
    "orders.load_id",
    "orders.customerid",
    "orders.consigneeid",
    "orders.vendorid",
    "orders.po",
    "orders.bol",
    "orders.pro",

    "orders.pickup",
    "orders.pickupLat",
    "orders.pickupLon",
    "orders.pickupdateFrom",
    "orders.pickupdateTo",
    "orders.pickupStreetAddress",
    "orders.pickupCompanyName",
    "orders.pickupCountry",
    "orders.pickupCountryCode",
    "orders.pickupState",
    "orders.pickupZip",
    "orders.pickupCity",
    "orders.pickupAccessorials",

    "orders.delivery",
    "orders.deliveryLat",
    "orders.deliveryLon",
    "orders.deliverydateFrom",
    "orders.deliverydateTo",
    "orders.deliveryStreetAddress",
    "orders.deliveryCompanyName",
    "orders.deliveryCountry",
    "orders.deliveryCountryCode",
    "orders.deliveryState",
    "orders.deliveryZip",
    "orders.deliveryCity",
    "orders.deliveryAccessorials",

    "orders.rate",
    "orders.permileRate",
    "orders.flatrate",
    "orders.fuelRate",
    "orders.otherRate",
    "orders.depoid",

    "orders.flowType",
    "orders.loadtype",
    "orders.weight",
    "orders.feet",
    "orders.cube",
    "orders.eta",
    "orders.ata",
    "orders.leaveTime",
    "orders.servicetime",
    "orders.timeInfo",
    "orders.timeWindows",
    "orders.pieceCount",
    "orders.loadTempIds",
    "orders.loadIds",
    "orders.flowTypes",
    "orders.proofSettings",
    "orders.proof",
    "orders.notes",
    "Customers.companyName",
    "Customers.customerName"
];

const OrdersAll = [
    "id",
    "orderNumber",
    "bol",
    "pro",
    "po",
    "companyId",
    "carrierid",
    "customerid",
    "loadnumber",
    "load_id",
    "isPlanned",
    "confirmed",
    "status",
    "statusInternal",
    "isFreezed",
    "depoid",
    "feet",
    "weight",
    "pallet",
    "cube",
    "currency",
    "rate",
    "rateType",
    "flatRate",
    "permileRate",
    "fuelRate",
    "fuelSurcharges",
    "otherRate",
    "eqType",
    "flowType",
    "loadtype",
    "pickupdateFrom",
    "pickupdateTo",
    "deliverydateFrom",
    "deliverydateTo",
    "delivery",
    "pickup",
    "deliveryCompanyName",
    "deliveryStreetAddress",
    "deliveryCity",
    "deliveryState",
    "deliveryZip",
    "deliveryCountry",
    "deliveryLon",
    "deliveryLat",
    "deliveryLocationtypeid",
    "deliveryAccessorials",
    "eta",
    "ata",
    "pickupCompanyName",
    "pickupStreetAddress",
    "pickupCity",
    "pickupState",
    "pickupZip",
    "pickupCountry",
    "pickupLon",
    "pickupLat",
    "pickupLocationtypeid",
    "pickupAccessorials",
    "dispatchDate",
    "servicetime",
    "notes",
    "productDescription",
    "custDistance",
    "custDuration",
    "specialneeds",
    "bh",
    "orderTypes",
    "createdAt",
    "updatedAt",
];

const Blocksdriver = [ 
    "id", 
    "fname", 
    "lname", 
    "status",
    "rate",
];

const Blocksload =   [ 
    "id", 
    "nickname", 
    "driverId",
    "depoId", 
    "flowType",
    "orders",
    "stops",
    "start",
    "startAddress", 
    "endAddress",
    "end",
    "startTime",
    "endTime",
    "dispatchDate",
    "deliveryDate",
    "feet",
    "weight",
    "cube",
    "pallet",
    "emptymile",
    "totalDistance",
    "totalDuration",
    "loadCost",
    "loadCostPerMile",
    "fuelSurcharge",
    "status",
    "freezed",
    "return",
    "planType",
    "comment",
    "totalcases",
    "lastlocatoins",
    "shiftId",
    "carTypes",
    "stopLocations"
];

const AutoplanAttributes = [
    "orders.id",
    "orders.feet",
    "orders.weight",
    "orders.cube",
    "orders.flowType",
    "orders.deliveryLat",
    "orders.deliveryLon",
    "orders.pickupLat",
    "orders.pickupLon",
    "orders.deliverydateFrom",
    "orders.deliverydateTo",
    "orders.pickupdateFrom",
    "orders.pickupdateTo",
    "orders.servicetime",
    "orders.eta",
    "orders.ata",
    "orders.timeWindows",
    "orders.pieceCount",
    "orders.consigneeid",
    "orders.mustbefirst as mustBeFirst",
    "consignees.driverId as driverId",
    "consignees.czone_id as zoneId"
];
const OrderAttr = [
    ...NorderAttrb,
    "statuses.color as statusColor",
    "statuses.id as statusId",
    "statuses.name as statusName",
    "statuses.statustype as statusType",
    "transporttypes.name as LoadType",
];

module.exports = {
    AutoplanAttributes,
    NorderAttrb,
    OrdersAll,
    Blocksdriver,
    Blocksload,
    OrderAttr
};